service: test-test

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SNS_ARN:
      Ref: SNSTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "sqs:*"
          Resource: !GetAtt SQSQueue.Arn
        - Effect: Allow
          Action:
            - 'sns:*'
          Resource:
            Ref: SNSTopic
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: /**/*.test.js

package:
  individually: true

functions:
  getProductsList:
    handler: functions/getProductsList.default
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: functions/getProductsById.default
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: functions/createProduct.default
    events:
      - http:
          path: /products
          method: post
          cors: true
  catalogBatchProcess:
    handler: functions/catalogBatchProcess.default
    events:
      - sqs:
          batchSize: 5
          arn: !GetAtt SQSQueue.Arn

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:SNS_EMAIL}
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSCustomSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:SNS_EMAIL_2}
        Protocol: email
        TopicArn:
          Ref: SNSTopic
        FilterPolicy:
          expensive:
            - 'true'
  Outputs:
    SQSUrl:
      Value:
        Ref: SQSQueue
      Export:
        Name: SQSUrl
    SQSQueueArn:
      Value: !GetAtt SQSQueue.Arn
      Export:
        Name: SQSQueueArn
    SNSTopic:
      Value:
        Ref: SNSTopic
      Export:
        Name: SNSTopic
    SNSSubscription:
      Value:
        Ref: SNSSubscription
      Export:
        Name: SNSSubscription