service: test-test

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: /**/*.test.js

package:
  individually: true

functions:
  getProductsList:
    handler: functions/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: functions/getProductsById.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: functions/createProduct.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true

# functions:

#   # getProductsList: 
#   # path: /products
#   # getProductsById 
#   # path /products/{productId}
#   # createProduct 
#   # path: /products  (POST)
  